package com.example.pricemanager.message;

public enum Action {
    LOGIN,
    REGISTRATION,
    CHECK_ROLE,
    EXIT,
    ADD_NEW_COMPANY,
    GET_ALL_USER_COMPANIES,
    UPDATE_COMPANY,
    DELETE_COMPANY,
    ADD_NEW_PRODUCT,
    GET_ALL_COMPANY_PRODUCTS,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    ADD_NEW_PRODUCTION,
    GET_ALL_PRODUCT_PRODUCTIONS,
    UPDATE_PRODUCTION,
    DELETE_PRODUCTION
}

